/// ============================================
/// Paystack Service — ShopPOS
/// ============================================
/// Wraps the two backend endpoints:
///   POST /api/momo/charge
///   GET  /api/momo/verify/:reference
///
/// The Paystack secret key NEVER appears here.
/// All sensitive calls go through the Node
/// Express backend (see backend/server.js).
/// ============================================
library;

import 'package:dio/dio.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';

import '../core/constants/app_constants.dart';
import '../models/paystack_models.dart';
import '../providers/backend_config_provider.dart';
import 'payment_gateway.dart';

// ── Provider ──────────────────────────────────────────────────────────────────

final paystackServiceProvider = Provider<PaymentGateway>((ref) {
  final baseUrl = ref.watch(backendUrlProvider);
  return PaystackService(baseUrl: baseUrl);
});

// ── Service ───────────────────────────────────────────────────────────────────

/// HTTP client that proxies Paystack Ghana MoMo calls through the local
/// Node/Express backend so the secret key never lives in the Flutter app.
class PaystackService implements PaymentGateway {
  late final Dio _dio;
  final String _baseUrl;

  PaystackService({String? baseUrl})
      : _baseUrl = baseUrl ?? AppConstants.backendBaseUrl {
    _dio = Dio(
      BaseOptions(
        baseUrl: _baseUrl,
        // Increased connect and receive timeouts to 30 seconds for slower networks
        connectTimeout: const Duration(seconds: 30),
        receiveTimeout: const Duration(seconds: 30),
        headers: {'Content-Type': 'application/json'},
      ),
    );
  }

  String get baseUrl => _baseUrl;

  /// Health check endpoint verification to validate backend connectivity immediately.
  @override
  Future<bool> testConnection([String? targetUrl]) async {
    final url = targetUrl ?? _baseUrl;
    try {
      final testDio = Dio(
        BaseOptions(
          connectTimeout: const Duration(seconds: 8),
          receiveTimeout: const Duration(seconds: 8),
        ),
      );
      final healthEndpoint = url.endsWith('/api')
          ? '${url.substring(0, url.length - 4)}/health'
          : '$url/health';
      final response = await testDio.get<Map<String, dynamic>>(healthEndpoint);
      return response.statusCode == 200 && response.data?['status'] == 'ok';
    } catch (_) {
      return false;
    }
  }

  // ── initiateCharge ────────────────────────────────────────────────────────

  /// Initiates a Ghana Mobile Money charge.
  ///
  /// [phone] must be in international format (e.g. "+233551234987").
  /// [amountGhs] is in Ghana Cedis — converted to pesewas internally.
  /// [provider] must be "mtn", "vod", or "tgo".
  /// [reference] is a unique transaction ID generated by the caller.
  ///
  /// Returns a [PaystackChargeResult] whose [status] will normally be
  /// [PaystackChargeStatus.pending] — the customer has not yet approved.
  @override
  Future<PaystackChargeResult> initiateCharge({
    required String phone,
    required double amountGhs,
    required String provider,
    required String reference,
  }) async {
    // Paystack amounts are always in the smallest currency unit (pesewas).
    final amountPesewas = (amountGhs * 100).round();

    try {
      final response = await _dio.post<Map<String, dynamic>>(
        '/momo/charge',
        data: {
          'phone': phone,
          'amount_pesewas': amountPesewas,
          'provider': provider,
          'reference': reference,
        },
      );

      final body = response.data;
      if (body == null) {
        return PaystackChargeResult.error('Empty response from backend.');
      }
      return PaystackChargeResult.fromJson(body);
    } on DioException catch (e) {
      final serverMessage = e.response?.data is Map
          ? (e.response?.data as Map)['message'] as String? ?? e.message
          : e.message;
      return PaystackChargeResult.error(
        'Network error: ${serverMessage ?? 'Could not reach payment server'}',
      );
    } catch (e) {
      return PaystackChargeResult.error('Unexpected error: $e');
    }
  }

  // ── verifyStatus ──────────────────────────────────────────────────────

  /// Polls the backend to check if a transaction has been approved.
  ///
  /// The app calls this every [AppConstants.momoPollingIntervalSec] seconds
  /// until the status resolves to success, failed, or abandoned, or until
  /// [AppConstants.momoTimeoutSec] elapses.
  @override
  Future<PaystackVerifyResult> verifyStatus(String reference) async {
    try {
      final response = await _dio.get<Map<String, dynamic>>(
        '/momo/verify/$reference',
      );

      final body = response.data;
      if (body == null) return PaystackVerifyResult.networkError();
      return PaystackVerifyResult.fromJson(body);
    } on DioException catch (_) {
      return PaystackVerifyResult.networkError();
    } catch (_) {
      return PaystackVerifyResult.networkError();
    }
  }
}

// ── Phone number utilities ────────────────────────────────────────────────────

/// Validates and normalises a Ghana phone number.
///
/// Accepts:
///   0XXXXXXXXX      (10 digits, local format)
///   +233XXXXXXXXX   (12 chars, international format)
///   233XXXXXXXXX    (11 digits, no leading +)
///
/// Returns the normalised international form (+233XXXXXXXXX), or null if invalid.
String? normaliseGhanaPhone(String raw) {
  final digits = raw.replaceAll(RegExp(r'[\s\-()]'), '');

  if (digits.startsWith('+233') && digits.length == 13) {
    return digits; // already correct
  }
  if (digits.startsWith('233') && digits.length == 12) {
    return '+$digits';
  }
  if (digits.startsWith('0') && digits.length == 10) {
    return '+233${digits.substring(1)}';
  }
  return null; // invalid
}

/// Returns a user-facing validation error string, or null if valid.
String? validateGhanaPhone(String raw) {
  if (raw.trim().isEmpty) return 'Phone number is required';
  if (normaliseGhanaPhone(raw) == null) {
    return 'Enter a valid Ghana number (e.g. 0551234987 or +233551234987)';
  }
  return null;
}
