/// ============================================
/// Paystack Service — ShopPOS
/// ============================================
/// Wraps the two backend endpoints:
///   POST /api/momo/charge
///   GET  /api/momo/verify/:reference
///
/// The Paystack secret key NEVER appears here.
/// All sensitive calls go through the Node
/// Express backend (see backend/server.js).
/// ============================================
library;

import 'package:dio/dio.dart';
import 'package:flutter/foundation.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';

import 'package:shop_pos/core/providers/store_settings_provider.dart';
import 'package:shop_pos/features/sales/models/paystack_models.dart';
import 'package:shop_pos/features/sales/services/payment_gateway.dart';

// ── Provider ──────────────────────────────────────────────────────────────────

final paystackServiceProvider = Provider<PaymentGateway>((ref) {
  final baseUrl = ref.watch(backendUrlProvider);
  final apiKey = ref.watch(storeSettingsProvider).syncApiKey.trim();
  return PaystackService(baseUrl: baseUrl, apiKey: apiKey);
});

// ── Service ───────────────────────────────────────────────────────────────────

/// HTTP client that proxies Paystack Ghana MoMo calls through the local
/// Node/Express backend so the secret key never lives in the Flutter app.
class PaystackService implements PaymentGateway {
  late final Dio _dio;
  final String _baseUrl;

  /// [baseUrl] is '' when no backend is configured; charges then fail
  /// with a clear message instead of trying an unreachable address.
  /// [apiKey] is sent as `x-api-key` when the backend requires one.
  /// [httpAdapter] replaces the network layer (tests only).
  PaystackService({
    required String baseUrl,
    String apiKey = '',
    @visibleForTesting HttpClientAdapter? httpAdapter,
  }) : _baseUrl = baseUrl {
    _dio = Dio(
      BaseOptions(
        baseUrl: _baseUrl,
        // Increased connect and receive timeouts to 30 seconds for slower networks
        connectTimeout: const Duration(seconds: 30),
        receiveTimeout: const Duration(seconds: 30),
        headers: {
          'Content-Type': 'application/json',
          if (apiKey.isNotEmpty) 'x-api-key': apiKey,
        },
      ),
    );
    if (httpAdapter != null) _dio.httpClientAdapter = httpAdapter;
  }

  String get baseUrl => _baseUrl;

  bool get isConfigured => _baseUrl.isNotEmpty;

  static const notConfiguredMessage =
      'Mobile Money is not set up. Ask the owner to enter the backend URL '
      'in Settings → Integrations.';

  /// Health check endpoint verification to validate backend connectivity immediately.
  @override
  Future<bool> testConnection([String? targetUrl]) async {
    final url = targetUrl ?? _baseUrl;
    if (url.isEmpty) return false;
    try {
      final testDio = Dio(
        BaseOptions(
          connectTimeout: const Duration(seconds: 8),
          receiveTimeout: const Duration(seconds: 8),
        ),
      );
      final healthEndpoint = url.endsWith('/api')
          ? '${url.substring(0, url.length - 4)}/health'
          : '$url/health';
      final response = await testDio.get<Map<String, dynamic>>(healthEndpoint);
      return response.statusCode == 200 && response.data?['status'] == 'ok';
    } catch (_) {
      return false;
    }
  }

  // ── initiateCharge ────────────────────────────────────────────────────────

  /// Initiates a Ghana Mobile Money charge.
  ///
  /// [phone] must be in international format (e.g. "+233551234987").
  /// [amountGhs] is in Ghana Cedis — converted to pesewas internally.
  /// [provider] must be "mtn", "vod", or "atl".
  /// [reference] is a unique transaction ID generated by the caller.
  ///
  /// Returns a [PaystackChargeResult] whose [status] will normally be
  /// [PaystackChargeStatus.pending] — the customer has not yet approved.
  @override
  Future<PaystackChargeResult> initiateCharge({
    required String phone,
    required double amountGhs,
    required String provider,
    required String reference,
    String? email,
  }) async {
    if (!isConfigured) {
      return PaystackChargeResult.error(notConfiguredMessage, code: 'not_configured');
    }

    // Paystack amounts are always in the smallest currency unit (pesewas).
    final amountPesewas = (amountGhs * 100).round();

    try {
      final response = await _dio.post<Map<String, dynamic>>(
        '/momo/charge',
        data: {
          'phone': phone,
          'amount_pesewas': amountPesewas,
          'provider': provider,
          'reference': reference,
          if (email != null && email.trim().isNotEmpty) 'email': email.trim(),
        },
      );

      final body = response.data;
      if (body == null) {
        return PaystackChargeResult.error('Empty response from backend.', outcomeUnknown: true);
      }
      return PaystackChargeResult.fromJson(body);
    } on DioException catch (e) {
      final response = e.response;
      if (response == null) {
        // No reply: the request may or may not have reached Paystack.
        return PaystackChargeResult.error(
          'Could not reach the payment server. Check the internet connection.',
          code: 'network_error',
          outcomeUnknown: true,
        );
      }
      final data = response.data is Map ? response.data as Map : const {};
      final code = data['error'] as String?;
      return PaystackChargeResult.error(
        switch (response.statusCode) {
          401 => 'The payment server rejected this till\'s API key. Ask the owner to check '
              'Settings → Integrations.',
          _ => data['message'] as String? ?? 'The payment request failed (HTTP ${response.statusCode}).',
        },
        code: code,
        // Paystack unreachable / erroring: the charge may still exist.
        outcomeUnknown: code == 'paystack_unreachable' || code == 'paystack_error',
      );
    } catch (e) {
      return PaystackChargeResult.error('Unexpected error: $e', outcomeUnknown: true);
    }
  }

  // ── verifyStatus ──────────────────────────────────────────────────────

  /// Polls the backend to check if a transaction has been approved.
  ///
  /// The app calls this every [AppConstants.momoPollingIntervalSec] seconds
  /// until the status resolves to success, failed, or abandoned, or until
  /// [AppConstants.momoTimeoutSec] elapses.
  @override
  Future<PaystackVerifyResult> verifyStatus(String reference) async {
    if (!isConfigured) return PaystackVerifyResult.networkError();
    try {
      final response = await _dio.get<Object>(
        '/momo/verify/${Uri.encodeComponent(reference)}',
        // Read error replies too: a 404 "not found" or 401 is an answer,
        // not a network failure.
        options: Options(validateStatus: (_) => true),
      );

      final status = response.statusCode ?? 0;
      final body = response.data;
      if (status == 200 && body is Map) {
        return PaystackVerifyResult.fromJson(Map<String, dynamic>.from(body));
      }
      return PaystackVerifyResult.fromError(status, body);
    } on DioException catch (_) {
      return PaystackVerifyResult.networkError();
    } catch (_) {
      return PaystackVerifyResult.networkError();
    }
  }
}

// ── Phone number utilities ────────────────────────────────────────────────────

/// Validates and normalises a Ghana phone number.
///
/// Accepts:
///   0XXXXXXXXX      (10 digits, local format)
///   +233XXXXXXXXX   (12 chars, international format)
///   233XXXXXXXXX    (11 digits, no leading +)
///
/// Returns the normalised international form (+233XXXXXXXXX), or null if invalid.
String? normaliseGhanaPhone(String raw) {
  final digits = raw.replaceAll(RegExp(r'[\s\-()]'), '');

  if (digits.startsWith('+233') && digits.length == 13) {
    return digits; // already correct
  }
  if (digits.startsWith('233') && digits.length == 12) {
    return '+$digits';
  }
  if (digits.startsWith('0') && digits.length == 10) {
    return '+233${digits.substring(1)}';
  }
  return null; // invalid
}

/// Returns a user-facing validation error string, or null if valid.
String? validateGhanaPhone(String raw) {
  if (raw.trim().isEmpty) return 'Phone number is required';
  if (normaliseGhanaPhone(raw) == null) {
    return 'Enter a valid Ghana number (e.g. 0551234987 or +233551234987)';
  }
  return null;
}
